name: auto-merge

on:
  pull_request:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: ahmadnassri/action-dependabot-auto-merge@master
        with:
          target: minor
          github-token: ${{ secrets.PARSONAL_ACCESS_TOKEN || secrets.GITHUB_TOKEN }}
