name: production deploy

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      # Build
      - name: build
        env:
          GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}
          VSSUE_ID: ${{ secrets.VSSUE_ID }}
          VSSUE_SECRET: ${{ secrets.VSSUE_SECRET }}
          GOOGLE_SITE_VERIFICATION_CONTENT: ${{ secrets.GOOGLE_SITE_VERIFICATION_CONTENT }}
        run: |
          yarn install
          yarn build

      # Deploy to Netlify
      - name: deploy
        uses: netlify/actions/cli@master
        with:
          args: deploy -d src/.vuepress/dist/ -p -m publish
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
